// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellBook.DataAccess;

#nullable disable

namespace SellBook.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SellBook.Models.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"), 1L, 1);

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Category_ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_ID = 1,
                            Category_Name = "Comestic",
                            CreatedDateTime = new DateTime(2023, 11, 7, 15, 49, 18, 919, DateTimeKind.Local).AddTicks(8212),
                            DisplayOrder = 1
                        },
                        new
                        {
                            Category_ID = 2,
                            Category_Name = "Family",
                            CreatedDateTime = new DateTime(2023, 11, 7, 15, 49, 18, 919, DateTimeKind.Local).AddTicks(8223),
                            DisplayOrder = 1
                        },
                        new
                        {
                            Category_ID = 3,
                            Category_Name = "History",
                            CreatedDateTime = new DateTime(2023, 11, 7, 15, 49, 18, 919, DateTimeKind.Local).AddTicks(8224),
                            DisplayOrder = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
